name: Deploy NuGet Package
on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v3

    - name: Setup .NET 
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0'
        
    - name: Build project
      run: dotnet build -c Release
      
    - name: Generate a NuGet package 
      run: dotnet pack --no-build -c Release -o .
      
    - name: Push to GitHub package registry
      run: dotnet nuget push "*.nupkg"  --skip-duplicate --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json 
